# Generated by Django 4.0.1 on 2022-01-16 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="quantity",
        ),
    ]
